# File: .github/workflows/keep-awake.yml
name: 💡 Keep Streamlit Awake

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'    # run at minute 0 of every hour

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: |
          echo "▶️ hitting https://accessreview.streamlit.app"
          STATUS=$(curl \
            --write-out '%{http_code}' \
            --silent \
            --output /dev/null \
            https://accessreview.streamlit.app)
          echo "✅ Streamlit responded with HTTP $STATUS"
          if [ "$STATUS" != "200" ]; then
            echo "::error::Expected 200 but got $STATUS"
            exit 1
          fi
