name: 🔆 Keep Streamlit Awake

# Runs automatically on the schedule below
on:
  schedule:
    # every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:  # also allows you to trigger it manually from Actions

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your repo
      - uses: actions/checkout@v4

      # 2) Configure Git so this commit looks sensible
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 3) Make an _empty_ commit (no content change) with the current timestamp
      - name: Empty-commit to reset sleep timer
        run: |
          git commit --allow-empty -m "chore: keep awake $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          git push
