# .github/workflows/keep-awake.yml
name: 💡 Keep Streamlit Awake

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */10 * * *'  # every hour

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the app (follow up to 5 redirects)
        run: |
          # follow up to 5 redirects, capture the final HTTP status
          STATUS=$(curl -sSL --max-redirs 5 \
                     -o /dev/null \
                     -w "%{http_code}" \
                     https://accessreview.streamlit.app || true)

          echo "▶️ Final HTTP status: $STATUS"

          # Only treat 2xx or 3xx as success
          if [[ "$STATUS" =~ ^[23][0-9][0-9]$ ]]; then
            echo "✅ App is up (or valid redirect)."
          else
            echo "❌ Unexpected status code: $STATUS"
            exit 1
          fi

